### PR TITLE
Fix broken link in devcontainer-rerference.md

### PR DESCRIPTION
**Pull request by tomlea**

### CODE REVIEW

**Review by 301166 — COMMENTED** [review]
I dont know what this

**Comment by 301166** [comment]
I dont know what this?

**Review by chrmarti — CHANGES_REQUESTED** [review]
Thanks for the PR! The existing link seems to work in the context it is used: https://containers.dev/implementors/spec/#image-metadata

**Review by Theghost256 — APPROVED** [review]

**Comment by tomlea** [comment]
> Thanks for the PR! The existing link seems to work in the context it is used: https://containers.dev/implementors/spec/#image-metadata

@chrmarti I can't find the page I ended up viewing it via in my browser history.
No special effort on my part to go anywhere specific… just googled my way to a page with a broken link.

Guessing I ended up on the GH repo rather than the generated site.

If it works both ways on the generated site (the other links seem to follow the same format), seems it would help poor lost souls like me.

Merge or no, I'm happy either way.

**Comment by chrmarti** [comment]
The update would change where the link points to on the website. Keeping it as-is. Thanks.

**Pull request closed without merging**
