### PR TITLE
Move proposals and add documentation

### PR DESCRIPTION
**Pull request by bamurtaugh**
Fixes https://github.com/devcontainers/spec/issues/338

As @samruddhikhandale proposed, we should move implemented proposals out of the "proposals" folder. I've made several changes in this PR:
* Move implemented proposals into the "specs" folder
* Update each implemented proposal to include a link to its initial discussion issue and where it was merged into the CLI or schema
* Add README content to the "specs" and "proposals" folder with more info on this process
     * In the "specs" README, included a list of the main top-level specs for easier navigation (i.e. overall dev container, Features, and Templates specs)
* Misc polish (i.e. caps, formatting)

I considered moving all of the proposals out of their individual files and instead into the existing spec files, but this felt less ideal: 
* It'd make the existing spec files much longer
     * Keeping a set of smaller individual files may better help with quick navigation 
* Each file can serve as a point in time reference to that proposal, including the discussion issue and implementation PR links

But if folks would prefer this ^, I'm happy to discuss further.

### CODE REVIEW

**Review by samruddhikhandale — APPROVED** [review]
Wow! This looks amazing, thank you so much for taking the time for making this change ✨

**Comment by samruddhikhandale** [comment]
> I considered moving all of the proposals out of their individual files and instead into the existing spec files, but this felt less ideal:

Makes sense to me! 👍

**Comment by bamurtaugh** [comment]
Thank you for the quick review @samruddhikhandale! And for the great idea that spurred this PR 😄. I'll merge now and happy to iterate in future PRs if other folks have additional thoughts.

**Comment by 113ll3** [comment]
bamurtaugh/move-props

**Review by 113ll3 — COMMENTED** [review]
proposals/README.md

**Comment by 113ll3** [comment]
.patch

**Pull request merged**
