### PR TITLE
Add build options

### PR DESCRIPTION
**Pull request by Roemer**
As in discussion https://github.com/devcontainers/spec/discussions/301, I would like to propose a way to add cli arguments to a `build` command, similar how `runArgs` add cli arguments to the `run` command.
This is needed for example for overriding the network eg. `network=host` or for adding additional hosts. There is also a discussion about it over at vscode-remote: https://github.com/microsoft/vscode-remote-release/issues/3545

Unfortunately, `build.args` is already used for Docker `ARG`uments so we need to use something else.
I am open for naming proposals.

Things I thought about are:
- build.buildArgs
- build.cliArgs
- build.cliOptions
- build.options
- build.commandArgs
- build.commandOptions

### CODE REVIEW

**Comment by Roemer** [comment]
@microsoft-github-policy-service agree

**Review by samruddhikhandale — COMMENTED** [review]
Hi 👋 

We appreciate your proposal of adding a new `build.cliOptions` property. However, I believe we are still missing the CLI changes?

We update the schema only after we release the respective CLI changes. I wonder if you were hoping to create a PR with a proposal ? (eg. https://github.com/devcontainers/spec/pull/196)

Feel free to look at https://containers.dev/implementors/contributing/#contribution-approaches for more details.

**Comment by Roemer** [comment]
So I should create a proposal markdown file similar to https://github.com/devcontainers/spec/pull/196? Can do. That should be in its own PR I suppose.

**Comment by samruddhikhandale** [comment]
As this was discussed in https://github.com/devcontainers/spec/discussions/301 and has decent amount of upvotes, I believe it should be alright not creating a spec issue (or maybe create one and link it to the discussion)

> So I should create a proposal markdown file similar to https://github.com/devcontainers/spec/pull/196?

Said that, it would be great if you can create a similar PR, if the proposal looks good then we can start thinking about the CLI code changes.

// cc @bamurtaugh Feel free to correct my understanding, if needed.

**Comment by Roemer** [comment]
I created a simple proposal for the spec change: https://github.com/devcontainers/spec/pull/328

**Comment by fossum** [comment]
@samruddhikhandale any update on this?

**Review by TateGunning — COMMENTED** [review]
Thank you

**Comment by chrmarti** [comment]
Updating the property name as agreed on in https://github.com/devcontainers/spec/pull/328.

**Review by eljog — APPROVED** [review]

**Review by Cynn1989 — APPROVED** [review]

**Review by travisnarlock1-code — APPROVED** [review]

**Comment by johnadames18-glitch** [comment]
``

**Review by Fleinsopp — COMMENTED** [review]
Change file diff

**Pull request merged**
